server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning?serverTimezone=Asia/Tokyo&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf 熱修用
  thymeleaf:
    cache: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl